### PR TITLE
Adds a script that outputs file with invocations of createBadge for copy paste

### PR DESCRIPTION
**Pull request by Schwartz10**
Hi Simon - the script is all set. A few things to note:

1. Most importantly, I'd like to have a fresh pair of eyes on Monday to double check everything is right before actually executing this script (quadruple checking the order of the `createBadge` args, cross-checking with etherscan to verify these transactions...etc). Would def appreciate your second pair of eyes as well. 

2. To run the script, go to the root directory of this repo and run `npm run initialize-badges`. If all goes smoothly you should see a new txt file appear in the `initializeBadges` directory.

3. Wasn't totally sure of the exact JSON we want in IPFS (thus for computing the nftCid), currently the nftCID is based off a JSON that looks like:

```
{
  "beneficiaryOfBadge": "0x1875e398cD7FdcE8fF5C9d4ce1Ec904caE51692c",
  "buyer": "0x374Bd185Ee19fD9f8682Eb875E5D0546A8D58CdD",
  "mgCid": "zdpuAs4oSTUXz9wJX8mY7LTztmrG6i6p1hjmMELgBV9iS1KdG",
  "usdCostOfBadge": "5"
}
```
It will be very easy to change this to whatever we want and include any other properties that are in the event logs, so just let me know. Although these are the only 4 arguments other than nftCid that are in the `createBadge` func.

4. I implemented the `pinToInfura` func recursively because it makes it much easier for us to simply `setTimeout` on our calls to infura if we end up reaching their rate limit (which happens at a very number of requests). If your script fails because of this error I'll throw back in the setTimeout, so just let me know.

5. Interesting aside about decoding params/logs: my first path was to imitate the event getter we created for the portal, but I had a crazy wrestling with web3 when trying to replicate it - the event filter wouldn't return ANYTHING - not an error or a result. I ended up using hardcoded data to unblock myself. Using the hardcoded data I was able to finish the script using decode logs / decode params like you shared with me, it worked great. Unfortunately, the decoding funcs ended up being totally useless because I changed the event getting strategy. However, I left the code from the original script in the `hardCodedData` file in case you're interested in seeing it semi-working. Happy to delete it when we merge this in. 

The web3 filter issue ended up being a weird bug that I spoke with some fellas from MetaMask and Infura about - it seems that we were trying to filter too many blocks in one request and it timed out. Conversation below in case you're interested:

https://consensys.slack.com/archives/G180E35GB/p1535130922000100
https://consensys.slack.com/archives/G180E35GB/p1535134448000100

### CODE REVIEW

**Comment by thomasbeta** [comment]
> Wasn't totally sure of the exact JSON we want in IPFS

I think we're trying to only push COALAIP objects to IPFS. Maybe we want to look at adding a new object using this a reference —> https://schema.org/BuyAction.

**Comment by Schwartz10** [comment]
@thomasbeta https://github.com/UjoTeam/contracts-badges/pull/19 has a couple comments that might help clarify why/how we're using IPFS here

**Comment by thomasbeta** [comment]
@Schwartz10 not sure if we're on the same page. Why couldn't we make a new COALAIP object for this?

**Comment by Schwartz10** [comment]
I see what you're saying, my bad. I definitely think it's better to use a coalaip object because it will enforce a standard that's easier to follow. Not sure how it plays into parsing the metadata from a token exchange's POV, but I'm sure Simon has insight into that

**Comment by Schwartz10** [comment]
hey @simondlr this is all set - I've confirmed 2 of the tx's on etherscan and they generally match what the script outputs (see below for why "generally").

If you go into the event logs on etherscan for a given transaction, the individual params in the `data` field are in a different order than when it comes back from a programmatic event getter. Additionally, the `cid` field is cut off after a certain amount of characters. Regardless, I can still verify an individual transaction by looking at the buyer, beneficiary, and the first x number of characters of the music group cid - as long as they all match I think we're good.

Example:
image
Should output badge script (notice the cutoff of mgcid from etherscan):
```
createBadge("0x374Bd185Ee19fD9f8682Eb875E5D0546A8D58CdD", "zdpuAs4oSTUXz9wJX8mY7LTztmrG6i6p1hjmMELgBV9iS1KdG", "zdpuB2o9vYZX7wmcm4tE43HUntsbm1uokD3rw5Vk4G2kP16oC", "0x1875e398cD7FdcE8fF5C9d4ce1Ec904caE51692c", 5);
```

Regardless, if you navigate to https://ipfs.infura.io:5001/api/v0/dag/get?arg=zdpuAs4oSTUXz9wJX8mY7LTztmrG6i6p1hjmMELgBV9iS1KdG (using the mgcid from the badge script), you will get a mg.

The last thing we need to discuss is the relationship between a single badge in IPFS and COALAIP.

**Comment by simondlr** [comment]
The nftCID needs to conform to the EIP721 metadata scheme. https://github.com/ethereum/EIPs/blob/master/EIPS/eip-721.md. That's how other sites/properties are pulling out data from NFTs atm.

The scheme is:

```
{
    "title": "Asset Metadata",
    "type": "object",
    "properties": {
        "name": {
            "type": "string",
            "description": "Identifies the asset to which this NFT represents",
        },
        "description": {
            "type": "string",
            "description": "Describes the asset to which this NFT represents",
        },
        "image": {
            "type": "string",
            "description": "A URI pointing to a resource with mime type image/* representing the asset to which this NFT represents. Consider making any images at a width between 320 and 1080 pixels and aspect ratio between 1.91:1 and 4:5 inclusive.",
        }
    }
}
```

Note: this is a schema. Adding the extra fields is optional and I think we should add them. Perhaps adding "dateCreated" would also be useful? The official fields will be readily re-used. The others might be more important for Ujo-specific apps, not generic NFT/collectible apps.

So, something like this would be the end-result:

```
{
    "name": "Sunset Simon Patronage Badge",
    "description": "<some description>",
    "image": "<image_uri>",
    "beneficiaryOfBadge": "0x1875e398cD7FdcE8fF5C9d4ce1Ec904caE51692c",
    "MusicGroup": "zdpuAs4oSTUXz9wJX8mY7LTztmrG6i6p1hjmMELgBV9iS1KdG",
    "usdCostOfBadge": "5",
    "dateCreated": "<timestamp>"
}
```

The rest LGTM. Glad getPastEvents is working so well!

**Comment by Schwartz10** [comment]
Cool, makes sense. A few q's:

1. Do you think we should include the buyer's address in this data too?
2. Which image should we use for the MG? Should we use the one associated with the current MGCID? @oftenfrequent this goes back to the "retro-badges" concept. 
3. Is the description generic or unique to each badge?

**Comment by simondlr** [comment]
> Do you think we should include the buyer's address in this data too?

I would say, no, because this doesn't make up the badge itself. It's only relevant at time of purchase.

> Which image should we use for the MG?

Since this nftCID doesn't change, it should be the one at the time of minting imho: like we had with the MGCID.

> Is the description generic or unique to each badge?

I would say it's generic, not like a band description. eg: "A collectible patronage badge for Sunset Simon."

Replacing "Sunset Simon" with the MG.

**Comment by Schwartz10** [comment]
Ok, did you see my updated question? 

> Also, not sure this matters at the moment, but I'm wondering if this script is missing an edge case which is if a badge had been transferred after purchase. I'm filtering for LogBadgeMinted events, so if we initialize badges we're giving ownership back to the original purchaser.

**Comment by simondlr** [comment]
> Also, not sure this matters at the moment, but I'm wondering if this script is missing an edge case which is if a badge had been transferred after purchase. I'm filtering for LogBadgeMinted events, so if we initialize badges we're giving ownership back to the original purchaser.

Yes, we need to check for this, but we can see if there's been any transfers, which doesn't look like it. You can see all txes are badge mint txes. No transfers have occurred yet.

https://etherscan.io/address/0xc45e027f0f9d7e90e612be02d4e710a632a9dba9

**Comment by Schwartz10** [comment]
```
{
  "beneficiaryOfBadge": "0x1875e398cD7FdcE8fF5C9d4ce1Ec904caE51692c",
  "dateCreated": "2018-07-30T22:42:05-04:00",
  "description": "A collectible patronage badge for Tom Finster",
  "image": "https://www.dev.ujomusic.com/image/600x600/https://ipfs.infura.io/ipfs/QmZnhUQ7Yr6XY86ERhkgHjQMQ8uqZ4hiMzmqPaZwLHNULA",
  "musicgroup": "zdpuAs4oSTUXz9wJX8mY7LTztmrG6i6p1hjmMELgBV9iS1KdG",
  "name": "Tom Finster Patronage Badge",
  "usdCostOfBadge": 5
}
```

This is all set, here's an example object from IPFS after running the script.

**Comment by simondlr** [comment]
Hey @Schwartz10. Removed the timestamps and the hardcoded data, along with some small tidying.

You can see an example of the nftCID here: https://ipfs.infura.io:5001/api/v0/dag/get?arg=zdpuAnZ4nv6cQoCj7tVVSmavg45HB5Dy7HkD8ubMvyH3z1CWq.

I'm still wondering about 3 things:

- Are all images being served dev URI? Don't we have a non-dev API up? 
- Should "musicgroup" field be linked in COALA IP style instead or perhaps just capitalise it? Or just keep lowercase as is?
-"https://www.dev.ujomusic.com/image/600x600/https://ipfs.infura.io/ipfs/QmZnhUQ7Yr6XY86ERhkgHjQMQ8uqZ4hiMzmqPaZwLHNULA". These URIs still worry me somewhat in terms of decentralization & future proofing. One can link straight to the IPFS URI. Would that be more future proof? In addition to that. Should we consider adding in a field that's "imageCID", that's just the IPFS hash? That keeps somewhat more future proof if any of the URIs go down.

**Comment by Schwartz10** [comment]
> Are all images being served dev URI? Don't we have a non-dev API up? decentralization & future proofing ?
Good catch, my latest commit changes this to live API. In terms of future proofing and decentralization, I see your point - the thoughts behind my decision here were that (1) The spec you posted has a description under image: 
```
Consider making any images at a width between 320 and 1080 pixels and aspect ratio between 1.91:1 and 4:5 inclusive.",
```
the api provides us a `600x600` image and potential big-time performance boosts.
(2) future proofing - one could capture the image cid from the URI even if it starts with `ujomusic.com/...` - by scraping the URI down to just the `ipfs.infura.io/ipfs/cid`, one can infer the infura uri, and then by scraping that URI down to just the `cid`, one can access the image directly from IPFS in worst case scenario

>Should "musicgroup" field be linked in COALA IP style instead or perhaps just capitalise it? Or just keep lowercase as is? 
Latest commit changes this to correct capitalization - seems redundant for IPFS to store the entire nest of MG information but would be interested in @thomasbeta opinion

**Comment by simondlr** [comment]
Agree on all counts. Feel its all "good enough" for now.

**Comment by simondlr** [comment]
I'm going to merge.

**Pull request merged**
