### PR TITLE
Multi-badge payments + recipients hash.

### PR DESCRIPTION
**Pull request by simondlr**

### CODE REVIEW

**Comment by simondlr** [comment]
My biggest wonder is around how to retrieve badges related to specific artists as their addresses & splits change with MsMG. It's generally a hard problem, contingent on whether people eventually try to "cheat" badges [buying badges of artists, but paying themselves]. Might eventually need to employ some verification or provenance.

But for now, it just needs to be "good enough" to ensure that badges can be bought with low barrier-to-entry and product/market fit tested.

But, in the short term, should recipientshash be over beneficiaries AND splits OR just beneficiaries? Does it matter?

Trade-off are that if splits are included in the hash it might be harder to track over time [that it's the same artist]. What's more likely to change?

@Schwartz10

**Comment by Schwartz10** [comment]
First of all, hats off to you getting the proxy-delegate structure working - its awesome. Simon and I had a conversation in slack about its innerworkings, as well as why the badge contract needs its own payment handler, so I'll summarize those discussions at the bottom of this comment in case people are interested or we need to come back to it later.

Originally my opinion was that `getRecipientsHash` should only hash the beneficiaries, but now I'm realizing that as long as the nftCid includes the `recipientsHash`, calculated in the same way (and ordering) as `getRecipientsHash` does, it won't really matter. We can use the nftCid to easily get the MG of the purchased badge, as well as verify that the payments were made to the appropriate members with appropriate splits by decoding the associated recipient hash (in IPFS), and verifying that hash against the one in the event logs. Does that make sense or was that gibberish?

Summary of discussion with Simon:

Q: why can't we use the `handler` contract to payout the proceeds of a badge, and then mint a new badge in the name of the buyer? (like we do for music release purchases)
A: The issue was that the beneficiary gets “lost” in the provenance if you do: User -> BadgeHandler -> Badges -> BadgeHandler. The beneficiary is the BadgeHandler itself. The beneficiary needs to ideally be the last payment, so you know who received it within the context of the Badges. eg, LogBadgeMinted. “Beneficiary” needs to be an artist, not another contract or something else.

Q: Is it actually useful to index the recipients hash? In order for it to be useful the ordering of the arguments that were hashed together has to be the same as it was when it was minted. Do you think it could be more helpful to index the mgCid?
A: The point is to keep track of who has been paid, since you can always spoof the mgCID.

Q: I'm pretty confused as to how the three contracts are all working together (proxy, delegate, proxystate)
A: Essentially: the proxy is static. All calls are routed through it. You set a delegated contract in the proxy. The calls come into the proxy and is then forward to the delegate. Using delegatecall, you execute the code in the state of the proxy. eg [lemme take your code, and execute it in this contract state]. That means you can upgrade/change functionality by changing the delegate. The proxy contract is responsible for actually making the delegate calls.

How proxystate works is more complicated. I added some comments in there, but requires some deeper understanding of Solidity. :slightly_smiling_face:

**Comment by simondlr** [comment]
> Originally my opinion was that getRecipientsHash should only hash the beneficiaries, but now I'm realizing that as long as the nftCid includes the recipientsHash, calculated in the same way (and ordering) as getRecipientsHash does, it won't really matter. We can use the nftCid to easily get the MG of the purchased badge, as well as verify that the payments were made to the appropriate members with appropriate splits by decoding the associated recipient hash (in IPFS), and verifying that hash against the one in the event logs.

This makes a lot of sense. In fact, since we rely on the nftCID, we can just take things out of the event logs and just rely on the nftCID to get the additional information.

The nftCID would be the ultimate identifier. We can then add the beneficiaries AND splits into the nftCID too [who was paid what for this badge].

Then in the smart contract you can take out superfluous hashing and other strings (eg mgcid) which will reduce the cost of minting by a nice amount.

And then, you emit only:

```tokenId, nftCID, usdCost, timeMinted, buyer, issuer, beneficiaries[], splits[]```

That way, in  the future, you can essentially determine "cheating" by comparing nft object's beneficiaries/splits and the one in the smart contract.

I'm going to run with this for now and see what gas cost savings look like.

What do you think @Schwartz10?

**Comment by simondlr** [comment]
Example of new nftCID: https://ipfs.infura.io:5001/api/v0/dag/get?arg=zdpuAviMaYYFTBiW54TLV11h93mB1txF6zccoF5fKpu9nsub8

**Pull request merged**
